lead_v = false

[[version_files]]
path = "version.txt"
version_prefix = "version: "
version_postfix = ""
[[version_files]]
path = "monster.toml"
version_prefix = "version = \""
version_postfix = "\"[^,]"
