[package]
name = "conventional-semver-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = "1.0.10"
conventional-commits-parser = "0.1.1"
git2 = "0.14"
clap = { version = "3.2.6", features = ["derive"] }
custom_error = "1.9.2"
