lead_v = false

[[version_files]]
path = "version.txt"
version_prefix = ""
version_postfix = ""
[[version_files]]
path = "monster.toml"
predefined = "cargo.toml"
version_prefix = "version = \""
version_postfix = "\"[^,]"
